name: cherokee-diffwave
channels:
  - pytorch-lts
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.0.0
  - aiohttp=3.7.4.post0
  - async-timeout=3.0.1
  - attrs=21.2.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.10.8
  - cachetools=4.2.4
  - certifi=2021.10.8
  - cffi=1.14.5
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=8.0.3
  - cryptography=35.0.0
  - cudatoolkit=11.1.74
  - dataclasses=0.8
  - ffmpeg=4.2.2
  - freetype=2.11.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=2.3.3
  - google-auth-oauthlib=0.4.6
  - grpcio=1.37.1
  - idna=3.1
  - importlib-metadata=4.8.2
  - intel-openmp=2021.4.0
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libidn2=2.3.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.15.8
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libvpx=1.7.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - markdown=3.3.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.1.0
  - ncurses=6.3
  - nettle=3.7.3
  - ninja=1.10.2
  - numpy=1.21.2
  - numpy-base=1.21.2
  - oauthlib=3.1.1
  - olefile=0.46
  - openh264=2.1.0
  - openssl=1.1.1l
  - pillow=8.4.0
  - pip=21.0.1
  - progressbar=2.5
  - protobuf=3.15.8
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pydub=0.25.1
  - pyjwt=2.3.0
  - pyopenssl=21.0.0
  - pysocks=1.7.1
  - python=3.7.11
  - python_abi=3.7
  - pytorch=1.8.2
  - pyu2f=0.1.5
  - readline=8.1
  - requests=2.26.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tbb=2021.3.0
  - tensorboard=2.7.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.0
  - tk=8.6.11
  - torchaudio=0.8.2
  - torchvision=0.9.2
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - urllib3=1.26.7
  - werkzeug=2.0.1
  - wheel=0.37.0
  - x264=1!157.20191217
  - xz=5.2.5
  - yarl=1.6.3
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - tqdm==4.62.3
