name: cherokee-diffwave
channels:
  - pytorch-lts
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cudatoolkit=11.1.74
  - ffmpeg=4.2.2
  - freetype=2.11.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - intel-openmp=2021.4.0
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libidn2=2.3.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libvpx=1.7.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - ninja=1.10.2
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openh264=2.1.0
  - openssl=1.1.1l
  - pillow=8.4.0
  - pip=21.0.1
  - pydub=0.25.1
  - python=3.7.11
  - python_abi=3.7
  - pytorch=1.8.2
  - readline=8.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - torchaudio=0.8.2
  - torchvision=0.9.2
  - typing_extensions=3.10.0.2
  - wheel=0.37.0
  - x264=1!157.20191217
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - diffwave==0.1.7
    - tqdm==4.62.3
